### PR TITLE
Define ngComponentLoaded class

### PR DESCRIPTION
**Pull request by kenneth-bolivar-castro**
Related with #81

### CODE REVIEW

**Comment by mrjmd** [comment]
I like this approach. If you can fix the conflict I will get this merged in. Thanks!

**Comment by kenneth-bolivar-castro** [comment]
@mrjmd it's already done, this PR has no longer conflict anymore, [yay](https://media.giphy.com/media/3o6Mbolqx8Ses8KXoQ/giphy.gif)!

**Comment by mrjmd** [comment]
Haha, nice!

Unfortunately I think you've got some cross contamination from the component path code in this branch now.

**Comment by kenneth-bolivar-castro** [comment]
@mrjmd well, now it's [ready!](https://media4.giphy.com/media/WZ4M8M2VbauEo/200.gif)

**Comment by kenneth-bolivar-castro** [comment]
It has took too much time without merged ~Opened on Jun 19, 2016

**Pull request closed without merging**
